package Acme::CPANLists::Import::Qiita::MojoliciousAdvent::2013;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://qiita.com/advent-calendar/2013/mojolicious] (retrieved on 2017-01-31). Visit the URL for the full contents.",entries=>[{module=>"Mojolicious"},{module=>"Mojolicious::Plugin::YmlConfig"},{module=>"YAML"},{module=>"Mojolicious::Plugin::Config"}],summary=>"Modules mentioned in Mojolicious Advent Calendar 2013 on Qiita.com"});

1;
# ABSTRACT: Modules mentioned in Mojolicious Advent Calendar 2013 on Qiita.com

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://qiita.com/advent-calendar/2013/mojolicious> (retrieved on 2017-01-31). Visit the URL for the full contents.

